services:
  nginx_server:
    hostname: nginx
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile_nginx
    ports:
      - "82:80"
    depends_on:
      - fastapi
    networks:
      - geopamplona_net

  postgis:
    hostname: postgis
    container_name: postgis
    build:
      context: .
      dockerfile: dockerfile_postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: geopamplona
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geopamplona_net

  fastapi:
    hostname: fastapi
    container_name: fastapi
    build:
      context: .
      dockerfile: dokcerfile_fastapi
    depends_on:
      - postgis
    ports:
      - "8000:8000"
    networks:
      - geopamplona_net
    

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.x
    container_name: geoserver
    hostname: geoserver
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver_data_dir:/opt/geoserver/geoserver_data
    restart: unless-stopped
    networks:
      - geopamplona_net


  # geoserver:
  #   hostname: geoserver
  #   container_name: geoserver
  #   build:
  #     context: .
  #     dockerfile: dockerfile_geoserver
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./tomcat/geoserver.war:/usr/local/tomcat/webapps/geoserver.war
  #   networks:
  #     - geopamplona_net
    
volumes:
  postgres_data:
  # geoserver_data:

networks:
  geopamplona_net:
    driver: bridge
