FROM postgis/postgis:latest
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=geopamplona
EXPOSE 5432

COPY ./postgis/postgresql.conf /etc/postgresql/postgresql.conf
COPY ./postgis/pg_hba.conf /etc/postgresql/pg_hba.conf

# Comando de arranque
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]