services:
  nginx_server:
    hostname: nginx
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile_nginx
    ports:
      - "82:80"
    depends_on:
      - fastapi
    networks:
      - geopamplona_net

  postgis:
    hostname: postgis
    container_name: postgis
    build:
      context: .
      dockerfile: dockerfile_postgis
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: geopamplona
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geopamplona_net

  fastapi:
    hostname: fastapi
    container_name: fastapi
    build:
      context: .
      dockerfile: dokcerfile_fastapi
    depends_on:
      - postgis
    ports:
      - "8000:8000"
    networks:
      - geopamplona_net
    

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.x
    container_name: geoserver
    hostname: geoserver
    ports:
      - "8081:8080"
    environment:
      GEOSERVER_ADMIN_PASSWORD: geoserver
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./geoserver/geoserver_config/web.xml:/opt/geoserver/webapps/geoserver/WEB-INF/web.xml
      - ./geoserver/shapefiles:/opt/geoserver/data/shapefiles
    restart: unless-stopped
    networks:
        - geopamplona_net

volumes:
  postgres_data:
  geoserver_data:

networks:
  geopamplona_net:
    driver: bridge
